services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    restart: unless-stopped
    ports:
      - "5678:5678"
    # Always start with tunnel for external integrations (Slack, Gmail, etc.)
    command: start --tunnel
    environment:
      # Timezone configuration (automatically detected or set via .env)
      - GENERIC_TIMEZONE=${TIMEZONE:-UTC}
      - TZ=${TIMEZONE:-UTC}
      
      # TUNNEL CONFIGURATION (automatically managed)
      # ==========================================
      - N8N_TUNNEL_URL=${N8N_TUNNEL_URL:-}
      - N8N_WEBHOOK_BASE_PATH=${N8N_WEBHOOK_BASE_PATH:-/webhook}
      
      # LOCAL DEVELOPMENT OPTIMIZED SETTINGS
      # =================================
      
      # Security settings (appropriate for local use)
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false  # Allow env access for local dev
      
      # Performance settings for local development
      - N8N_LOG_LEVEL=info
      - N8N_DIAGNOSTICS_ENABLED=false
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_MAX_AGE=168  # 7 days (shorter for local dev)
      
      # Workflow management optimized for local use
      - N8N_WORKFLOW_HISTORY_ENABLED=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      
      # Set workflows export path to mounted directory
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_TEMPLATES_ENABLED=true
      
    volumes:
      # Persistent data storage
      - n8n_data:/home/node/.n8n
      
      # Mount workflows directory as default export destination
      # Users can easily export finished workflows here
      - ./workflows:/opt/workflows
      
      # Mount directory for easy file sharing with workflows
      - ./shared-files:/files
      
    # Optional: Add custom networks or dependencies
    # depends_on:
    #   - postgres
    
    # Health check to ensure n8n is running properly
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local

# Optional: PostgreSQL database for production use
# Uncomment the section below if you want to use PostgreSQL instead of SQLite
#
# services:
#   postgres:
#     image: postgres:15
#     container_name: n8n_postgres
#     restart: unless-stopped
#     environment:
#       - POSTGRES_USER=n8n
#       - POSTGRES_PASSWORD=n8n_password
#       - POSTGRES_DB=n8n
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#
#   n8n:
#     # ... existing n8n configuration above ...
#     environment:
#       # ... existing environment variables ...
#       # Database configuration
#       - DB_TYPE=postgresdb
#       - DB_POSTGRESDB_DATABASE=n8n
#       - DB_POSTGRESDB_HOST=postgres
#       - DB_POSTGRESDB_PORT=5432
#       - DB_POSTGRESDB_USER=n8n
#       - DB_POSTGRESDB_PASSWORD=n8n_password
#       - DB_POSTGRESDB_SCHEMA=public
#     depends_on:
#       - postgres
#
# volumes:
#   postgres_data:
#     driver: local
