services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_local
    restart: unless-stopped
    ports:
      - "5678:5678"
    # Always start with tunnel for external integrations (Slack, Gmail, etc.)
    command: start --tunnel
    environment:
      # Timezone configuration (automatically detected or set via .env)
      - GENERIC_TIMEZONE=${TIMEZONE:-UTC}
      - TZ=${TIMEZONE:-UTC}
      
      # CORE N8N SETTINGS (matching working Docker command)
      # ==================================================
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      
      # TUNNEL CONFIGURATION (Let n8n generate fresh tunnel URLs)
      # =======================================================
      # Note: N8N_TUNNEL_URL removed - forces fresh tunnel generation
      
      # MINIMAL SETTINGS FOR TUNNEL COMPATIBILITY
      # ========================================
      # Only essential settings to avoid conflicts
      
    volumes:
      # Persistent data storage (matching working Docker command)
      - n8n_data:/home/node/.n8n
      
      # Mount workflows directory as default export destination
      # Users can easily export finished workflows here
      - ./workflows:/opt/workflows
      
      # Mount directory for easy file sharing with workflows
      - ./shared-files:/files

volumes:
  n8n_data:
    driver: local

# Optional: PostgreSQL database for production use
# Uncomment the section below if you want to use PostgreSQL instead of SQLite
#
# services:
#   postgres:
#     image: postgres:15
#     container_name: n8n_postgres
#     restart: unless-stopped
#     environment:
#       - POSTGRES_USER=n8n
#       - POSTGRES_PASSWORD=n8n_password
#       - POSTGRES_DB=n8n
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#
#   n8n:
#     # ... existing n8n configuration above ...
#     environment:
#       # ... existing environment variables ...
#       # Database configuration
#       - DB_TYPE=postgresdb
#       - DB_POSTGRESDB_DATABASE=n8n
#       - DB_POSTGRESDB_HOST=postgres
#       - DB_POSTGRESDB_PORT=5432
#       - DB_POSTGRESDB_USER=n8n
#       - DB_POSTGRESDB_PASSWORD=n8n_password
#       - DB_POSTGRESDB_SCHEMA=public
#     depends_on:
#       - postgres
#
# volumes:
#   postgres_data:
#     driver: local
